--[[
    This is where you can list the modules you want to load
    
    For more information see the wiki.
]]

function GetModFrameworkModulesCompMod()
    return {
        "Alien/BabblerMine",
        "Alien/BoneWall/Flammable",
        "Alien/Crag/Healing",
        "Alien/Cyst",
        "Alien/Drifters/HoverHeight",
        "Alien/Drifters/Uncloak",
        "Alien/Eggs/EmbryoHP",
        "Alien/Eggs/HiveEggHeal",
        "Alien/Eggs/LifeformEggDrops",
        "Alien/Enzyme/Cooldown",
        "Alien/Fade/AdvancedSwipe",
        "Alien/Fade/Stab",
        "Alien/Gorge/Babblers/Flammable",
        "Alien/Gorge/Babblers/Health",
        "Alien/Gorge/Babblers/SpawnRate",
        "Alien/Gorge/BileBomb/Research",
        "Alien/Gorge/Web/HealthPerCharge",
        "Alien/Gorge/Web/MaxCharges",
        "Alien/Gorge/Web/SlowDuration",
        "Alien/GorgeTunnels/HeightCheck",
        "Alien/GorgeTunnels/AlwaysInfested",
        "Alien/GorgeTunnels/Cost",
        "Alien/Hallucination/HealthAndShields",
        "Alien/Healing",
        "Alien/Lerk/Movement",
        "Alien/Lerk/Roost",
        "Alien/Lerk/Spikes",
        "Alien/Lerk/SporesBiomass",
        "Alien/Lerk/VampirismScalar",
        "Alien/Mucous/Cooldown",
        "Alien/Mucous/Radius",
        "Alien/Mucous/ShieldPercent",
        "Alien/Onos/BoneShield/ConsumeRate",
        "Alien/Onos/Charge/CollideWithPlayers",
        "Alien/Onos/Stomp",
        "Alien/Shift/Echo",
        "Alien/Skulk/BiteConeSize",
        "Alien/Skulk/InnateRegen",
        "Alien/Skulk/Leap",
        "Alien/Upgrades/Adrenaline",
        "Alien/Upgrades/Aura/Range",
        "Alien/Upgrades/Carapace",
        "Alien/Upgrades/Cloaking/MoveSpeed",
        "Alien/Upgrades/Crush",
        "Alien/Upgrades/Focus",
        "Alien/Upgrades/General",
        "Alien/Upgrades/Neurotoxin",
        "Alien/Upgrades/Regen",
        "Alien/Upgrades/Scavenger",
        "Alien/Upgrades/Tenacity",
        "Alien/Upgrades/Vampirism/FriendlyFireFix",
        "Alien/Upgrades/Vampirism/ShieldEffect",
    
        "Changelog",
    
        "Global/KeepLightsOnAtStart",
        "Global/MucousHitsounds",
        "Global/Resources",
    
        "Marine/AdvancedArmory/Health",
        "Marine/AdvancedWeapons",
        "Marine/ARC/Health",
        "Marine/Armory/UpgradeToAA",
        "Marine/CyberneticBoots",
        "Marine/Flamethrower",
        "Marine/HMG/Damage",
        "Marine/MAC/Cost",
        "Marine/Medpack",
        "Marine/MedpackHoT",
        "Marine/Nanoshield",
        "Marine/Observatory/BuildTime",
        "Marine/PrototypeLab/Cost",
        "Marine/RoboticsFactory/ARCFactoryResearch",
        "Marine/RoboticsFactory/Cost",
        "Marine/Sentry/Cost",
        "Marine/Sentry/SporesConfusion",
        "Marine/SentryBattery/Cost",
        "Marine/Shotgun/Damage",
        "Marine/Shotgun/Falloff",
        "Marine/SupplyChanges",
        "Marine/SlowExpirationRate",
        "Marine/WeaponDropTime",

        "QOL/ArmoryHPBarGlobalFix",
        "QOL/CommanderMetabFix",
        "QOL/FemaleSprintingSounds",
        "QOL/KeepUpgrades",
        "QOL/PreventMultipleInitialIPs",
        "QOL/ResponsiveGUI",
        "QOL/StatusIconsLowDetail",
    
        "Spectator/EdgePanning",
        "Spectator/HelpText",
        "Spectator/SupplyDisplay",
    }
end
