if not Client then return end

local blockableProps = debug.getupvaluex(MapParticlesOption_IsPropnameBlockable, "blockableProps")
blockableProps["ns2_biodamnnn"] = set
{
    "models/marine/dropship/dropship.model",
    "models/props/biodome/biobome_outdoor_rock_01.model",
    "models/props/biodome/biobome_outdoor_rock_02.model",
    "models/props/biodome/biobome_outdoor_rock_03.model",
    "models/props/biodome/biobome_outdoor_rock_04.model",
    "models/props/biodome/biodome_bamboo_01_01_high.model",
    "models/props/biodome/biodome_bamboo_01_01_low.model",
    "models/props/biodome/biodome_bamboo_01_02_high.model",
    "models/props/biodome/biodome_bamboo_01_02_low.model",
    "models/props/biodome/biodome_bamboo_01_03_high.model",
    "models/props/biodome/biodome_bamboo_01_03_low.model",
    "models/props/biodome/biodome_bamboo_01_04_high.model",
    "models/props/biodome/biodome_bamboo_01_04_low.model",
    "models/props/biodome/biodome_bamboo_01_05_high.model",
    "models/props/biodome/biodome_bamboo_01_05_low.model",
    "models/props/biodome/biodome_bamboo_clump_01_01_high.model",
    "models/props/biodome/biodome_bamboo_clump_01_01_low.model",
    "models/props/biodome/biodome_bamboo_clump_01_02_high.model",
    "models/props/biodome/biodome_bamboo_clump_01_02_low.model",
    "models/props/biodome/biodome_bamboo_clump_01_03_high.model",
    "models/props/biodome/biodome_bamboo_clump_01_03_low.model",
    "models/props/biodome/biodome_bamboo_clump_01_04_high.model",
    "models/props/biodome/biodome_bamboo_clump_01_04_low.model",
    "models/props/biodome/biodome_bamboo_clump_01_05_high.model",
    "models/props/biodome/biodome_bamboo_clump_01_05_low.model",
    "models/props/biodome/biodome_bamboo_crown_01_01.model",
    "models/props/biodome/biodome_bamboo_crown_01_02.model",
    "models/props/biodome/biodome_bamboo_crown_01_03.model",
    "models/props/biodome/biodome_bamboo_crown_01_04.model",
    "models/props/biodome/biodome_carousel_plants_01.model",
    "models/props/biodome/biodome_carousel_plants_02.model",
    "models/props/biodome/biodome_carousel_plants_03.model",
    "models/props/biodome/biodome_carousel_plants_04.model",
    "models/props/biodome/biodome_container_tree_01.model",
    "models/props/biodome/biodome_container_tree_02.model",
    "models/props/biodome/biodome_container_tree_03.model",
    "models/props/biodome/biodome_container_tree_04.model",
    "models/props/biodome/biodome_flower_01_high.model",
    "models/props/biodome/biodome_flower_02_low.model",
    "models/props/biodome/biodome_flower_03_low.model",
    -- "models/props/biodome/biodome_fruit_pods_01.model",
    -- "models/props/biodome/biodome_fruit_pods_02.model",
    -- "models/props/biodome/biodome_fruit_pods_03.model",
    -- "models/props/biodome/biodome_fruit_pods_04.model",
    "models/props/biodome/biodome_fruit_pods_grapes_01.model",
    "models/props/biodome/biodome_fruit_pods_grapes_02.model",
    "models/props/biodome/biodome_fruit_pods_melone.model",
    "models/props/biodome/biodome_fruit_pods_tomato_01.model",
    "models/props/biodome/biodome_fruit_pods_tomato_02.model",
    "models/props/biodome/biodome_fruit_pods_tomato_03.model",
    "models/props/biodome/biodome_outdoor_rock_boulder_01.model",
    "models/props/biodome/biodome_outdoor_rock_boulder_02.model",
    "models/props/biodome/biodome_outdoor_rock_pile_01.model",
    "models/props/biodome/biodome_outdoor_rock_pile_02.model",
    "models/props/biodome/biodome_outdoor_rock_pile_03.model",
    "models/props/biodome/biodome_outdoor_rock_smallpile_01.model",
    "models/props/biodome/biodome_outdoor_rock_smallpile_02.model",
    "models/props/biodome/biodome_outdoor_rock_smallpile_03.model",
    "models/props/biodome/biodome_outdoor_rock_smallpile_04.model",
    "models/props/biodome/biodome_outdoor_sandbank_01.model",
    "models/props/biodome/biodome_outdoor_sandbank_02.model",
    "models/props/biodome/biodome_outdoor_sandbank_03.model",
    "models/props/biodome/biodome_outdoor_sandbank_04.model",
    "models/props/biodome/biodome_outdoor_sandbank_05.model",
    "models/props/biodome/biodome_outdoor_terrain.model",
    "models/props/biodome/biodome_outdoor_terrain_wet.model",
    "models/props/biodome/biodome_plant_01_high.model",
    "models/props/biodome/biodome_plant_01_low.model",
    "models/props/biodome/biodome_plant_02_low.model",
    "models/props/biodome/biodome_plant_03_02_high.model",
    "models/props/biodome/biodome_plant_03_03_high.model",
    "models/props/biodome/biodome_plant_04_01_high.model",
    "models/props/biodome/biodome_plant_04_01_low.model",
    "models/props/biodome/biodome_plant_04_01_red_high.model",
    "models/props/biodome/biodome_plant_04_01_red_low.model",
    "models/props/biodome/biodome_plant_04_02_high.model",
    "models/props/biodome/biodome_plant_04_02_low.model",
    "models/props/biodome/biodome_plant_04_02_red_high.model",
    "models/props/biodome/biodome_plant_05_01_high.model",
    "models/props/biodome/biodome_plant_05_01_low.model",
    "models/props/biodome/biodome_plant_05_02_high.model",
    "models/props/biodome/biodome_plant_05_03_low.model",
    "models/props/biodome/biodome_plant_06_01_high.model",
    "models/props/biodome/biodome_plant_06_02_high.model",
    "models/props/biodome/biodome_plant_06_03_high.model",
    "models/props/biodome/biodome_plant_07_high.model",
    -- "models/props/biodome/biodome_robot_arm.model",
    "models/props/biodome/biodome_special_plant_01.model",
    "models/props/biodome/biodome_tray_b_01.model",
    "models/props/biodome/biodome_tray_b_02.model",
    "models/props/biodome/biodome_tray_b_03.model",
    "models/props/biodome/biodome_tree_01_high.model",
    "models/props/biodome/biodome_tree_01_low.model",
    "models/props/biodome/biodome_tree_02_high.model",
    "models/props/biodome/biodome_tree_02_low.model",
    "models/props/biodome/biodome_tree_03.model",
    "models/props/descent/descent_satellitearray_dish.model",
    "models/props/docking/docking_landingshield_brace.model",
    "models/props/docking/docking_plants_01_plant1.model",
    "models/props/refinery/mining_light_04.model",
    "models/props/refinery/refinery_rockhard_09.model",
    "models/props/refinery/refinery_rock_bot_str_256.model",
    "models/props/refinery/refinery_rock_large_01.model",
    "models/props/refinery/refinery_rock_ledge_01.model",
    "models/props/refinery/refinery_rock_ledge_02.model",
    "models/props/refinery/refinery_rock_mid_str_128.model",
    "models/props/refinery/refinery_rock_pile_03.model",
    "models/props/refinery/refinery_skytowers_landingpad.model",
}

local loadTypes = debug.getupvaluex(LoadMapEntity, "loadTypes")
local LoadStaticProp = loadTypes["prop_static"].LoadFunction
debug.setupvaluex(LoadStaticProp, "blockableProps", blockableProps)
loadTypes["prop_static"].LoadFunction = LoadStaticProp
debug.setupvaluex(LoadMapEntity, "loadTypes", loadTypes)

debug.setupvaluex(MapParticlesOption_IsPropnameBlockable, "blockableProps", blockableProps)

MapParticlesOption_RemoveBlockableProps()
MapParticlesOption_RecreateBlockableProps()