local techHandler = CompMod:GetModule('techhandler')
techHandler:ChangeTechData(kTechId.BuildTunnelEntryOne, {[kTechDataMaxExtents] = Vector(1.2, 0.3, 1.2)})
techHandler:ChangeTechData(kTechId.BuildTunnelEntryTwo, {[kTechDataMaxExtents] = Vector(1.2, 0.3, 1.2)})
techHandler:ChangeTechData(kTechId.BuildTunnelEntryThree, {[kTechDataMaxExtents] = Vector(1.2, 0.3, 1.2)})
techHandler:ChangeTechData(kTechId.BuildTunnelEntryFour, {[kTechDataMaxExtents] = Vector(1.2, 0.3, 1.2)})
techHandler:ChangeTechData(kTechId.Tunnel, {[kTechDataMaxExtents] = Vector(1.2, 0.3, 1.2)})
techHandler:ChangeTechData(kTechId.TunnelRelocate, {[kTechDataMaxExtents] = Vector(1.2, 0.3, 1.2)})